use_rc_failsafe: false
rc_failsafe_threshold: 1500         # [1000, 2000]
rc_failsafe_channel: 9              # indexing from 1
diagnostics_rate: 1                 # publish diagnostics at n Hz
diagnostic_tracking_threshold: 1    # [m] distance considered as "in place" 

# mrs collision avoidance
mrs_collision_avoidance:
  enable: true
  trajectory_timeout: 2.0 # [s]
  drone_names: [uav1, uav2, uav3, uav4, uav5, uav7, uav8, uav11, uav12, uav13, uav14, uav15]
  radius: 5.0 # [m]
  altitude_threshold: 2.95 # [m]
  correction: 3.0 # [m] 
  predicted_trajectory_publish_rate: 2 # [Hz]
  collision_horizontal_speed_coef: 0.25 # when collision detected, slow down during the manouver
  collision_horizontal_acceleration_coef: 0.5 # when collision detected, keep the acceleration down during the manouvre 
  collision_slow_down_before: 10 # when collision detected, slow down this number of steps before it
  collision_slowing_hysteresis: 2.0 # [s] prolonging the slowing 

dynamicalModel:
  numberOfStates: 9
  numberOfInputs: 3
  dt: 0.01
  dt2: 0.2
  
  A: [1, 0.01, 0, 0, 0, 0, 0, 0, 0,
      0, 1, 0.01, 0, 0, 0, 0, 0, 0,
      0, 0, 1, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 1, 0.01, 0, 0, 0, 0,
      0, 0, 0, 0, 1, 0.01, 0, 0, 0,
      0, 0, 0, 0, 0, 1, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 1, 0.01, 0,
      0, 0, 0, 0, 0, 0, 0, 1, 0.01,
      0, 0, 0, 0, 0, 0, 0, 0, 1]
  
  A2: [1, 0.2, 0, 0, 0, 0, 0, 0, 0,
      0, 1, 0.2, 0, 0, 0, 0, 0, 0,
      0, 0, 1, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 1, 0.2, 0, 0, 0, 0,
      0, 0, 0, 0, 1, 0.2, 0, 0, 0,
      0, 0, 0, 0, 0, 1, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 1, 0.2, 0,
      0, 0, 0, 0, 0, 0, 0, 1, 0.2,
      0, 0, 0, 0, 0, 0, 0, 0, 1]
  
  B: [0, 0, 0,
      0, 0, 0,
      0.01, 0, 0,
      0, 0, 0,
      0, 0, 0, 
      0, 0.01, 0,
      0, 0, 0,
      0, 0, 0,
      0, 0, 0.01]

  B2: [0, 0, 0,
       0, 0, 0,
       0.2, 0, 0,
       0, 0, 0,
       0, 0, 0, 
       0, 0.2, 0,
       0, 0, 0,
       0, 0, 0,
       0, 0, 0.2]

yawTracker:
  yawGain: 1.0
  maxYawRate: 1.0

mpc:  
  horizon_len: 40
  numberOfVariables: 33
  maxTrajectorySize: 5000

  maxHorizontalSpeed: 7.0
  maxHorizontalAcceleration: 1.65

  maxVerticalAscendingSpeed: 2.0
  maxVerticalAscendingAcceleration: 1.0

  maxVerticalDescendingSpeed: 1.0
  maxVerticalDescendingAcceleration: 2.0

  maxAltitude: 15.0

  trackingErrorThr: 2.0

  Q: [5000, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 800, 0, 0, 0, 0, 0, 0,
      0, 800, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 5000, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 800, 0, 0, 0,
      0, 0, 0, 0, 800, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 5000, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 800,
      0, 0, 0, 0, 0, 0, 0, 800, 0]
  
  Q2: [5000, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 460, 0, 0, 0, 0, 0, 0,
      0, 460, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 5000, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 460, 0, 0, 0,
      0, 0, 0, 0, 460, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 5000, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 460,
      0, 0, 0, 0, 0, 0, 0, 460, 0]
  
  P: [500, 0, 0,
      0, 500, 0,
      0, 0, 500]

  U: [1, 1, 1, 1, 1, 5, 5, 5, 5, 5, 10] 
