tracker_loop_rate: 100 # [Hz]

takeoff_height: 3.0
landing_fast_height: 2.0
landing_height: -0.25
landing_cutoff_height: 0.30

max_position_difference: 0.5

horizontal_tracker:
  horizontal_speed: 4.0
  horizontal_acceleration: 1.0

vertical_tracker:
  vertical_speed: 1.0
  vertical_acceleration: 1.0

  takeoff_speed: 1.0
  takeoff_acceleration: 1.0

  landing_speed: 0.3
  landing_acceleration: 0.1

yaw_tracker:
  yaw_gain: 0.4
  yaw_rate: 1.0
