tracker_loop_rate: 100 # [Hz]

horizontal_tracker:
  horizontal_speed: 1.0
  horizontal_acceleration: 0.5
  
approaching_tracker:
  approaching_speed: 0.1
  approaching_acceleration: 0.05

stabilize_tracker:
  stabilize_speed: 0.2
  stabilize_acceleration: 0.1

vertical_tracker:
  vertical_speed: 1.0
  vertical_acceleration: 0.5

yaw_tracker:
  yaw_gain: 0.3
  yaw_rate: 0.3

max_tilt: 0.5 
